include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    # Otras reglas útiles
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true